### ISSUE TITLE
Names of documents in Russian is displayed in the online editor marks ???

### ISSUE THREAD

**Issue by KillBill2016** [cetra3/onlyoffice-alfresco#11]
Share plugin enables users to edit Office documents within Onlyoffice from Alfresco Share.
Sorry bad english http://pastenow.ru/IVAP

**Comment by cetra3** [comment]
Hi @KillBill2016,

A couple of questions:
- What should the document name be.  Can you give us an example of which cyrillic characters are displayed as question marks?
- If you use OnlyOffice by itself by going to `http://<onlyoffice_url/OnlineEditorsExample/` and uploading the file, does it show correctly?

This might either be because the font that OnlyOffice uses has a limited character set, or UTF-8 encoding is not working in some spot.

**Comment by KillBill2016** [comment]
What should the document name be. Can you give us an example of which cyrillic characters are displayed as question marks? - Any name is displayed signs ????? 
Example of which cyrillic characters - Запорожье (Рабочая копия).xlsx

If you use OnlyOffice by itself by going to http://<onlyoffice_url/OnlineEditorsExample/ and uploading the file, does it show correctly? -Yes, correctly

Sorry bad english

**Comment by cetra3** [comment]
Ok, I can replicate that here.  Appears to be an issue when encoding to JSON.  I will see if I can resolve it.

**Comment by cetra3** [comment]
@KillBill2016 
Please download the new version:
https://github.com/cetra3/onlyoffice-alfresco/releases/tag/1.0.3

**Comment by KillBill2016** [comment]
Thank you so much, with a new plug-in 1.0.3 file name is displayed correctly
